### ISSUE TITLE
Research Page

### ISSUE THREAD

**Issue by ColeMiles** [spsatuva/spsatuva.github.io#1]
Create a page that has links to professor's pages who are accepting undergraduate research assistants.

**Comment by stevenstetzler** [comment]
I made major changes to the research page and added a general outline of what should be on there.

To-Do:
- Integrate REU summaries effectively (either docs / HTML versions of the PDFs, integrating PDFs directly looks hard)
- Check for typos
- Distribute information across multiple pages (?)

**Comment by stevenstetzler** [comment]
Add: Poster information and tips

Otherwise, done.

**Comment by stevenstetzler** [comment]
Finished
