### ISSUE TITLE
Grad School / GRE Page

### ISSUE THREAD

**Issue by ColeMiles** [spsatuva/spsatuva.github.io#3]
Create a page with information about applying to grad schools and studying for the GRE. (Same page or separate?)

**Comment by Mattwalker411** [comment]
I made the pages and added a few links. We need more links for the "applying to grad school page"

**Comment by Mattwalker411** [comment]
Finished for now

**Comment by stevenstetzler** [comment]
Note: Would add links to GRE dates and registration deadlines

**Comment by stevenstetzler** [comment]
Done: <https://spsatuva.github.io/resources/grad-school/>
