### ISSUE TITLE
Front Page Layout

### ISSUE THREAD

**Issue by ColeMiles** [spsatuva/spsatuva.github.io#5]
Decide how the front page will be laid out, with links to other pages / pictures.

**Comment by stevenstetzler** [comment]
I'm envisioning that the big image on the front page is replaced with an image slider, but it has the same "Society of Physics Students" title on each image. Below that, it would be nice to copy the [math dept page](http://math.virginia.edu/). Blog cards on the left and a calendar of events on the right.

**Comment by stevenstetzler** [comment]
Added image slider to front page instead of static hero image.
